title: Charlotte's Portfolio
description: A thoughtful portfolio of Charlotte's work, ideas, and experiments.
url: "https://birdrodent.com"
baseurl: ""
remote_theme: yousinix/portfolYOU
open_new_tab: false

markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jemoji

author:
  name: Charlotte
  image: /Charlottepfp.jpg
  email: hello@birdrodent.com
  github: birdrodent

permalink: /blog/:title

collections:
  projects:
    output: true
    permalink: /projects/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: page

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md